//! Custom certificate verification for WezTerm.
//!
//! WezTerm uses self-signed certificates generated by the PKI system.
//! This module provides custom verifiers that:
//! 1. Accept certificates signed by a specific CA
//! 2. Verify the CN matches the Unix username (for mux authentication)

use anyhow::{anyhow, Result};
use rustls::client::danger::{HandshakeSignatureValid, ServerCertVerified, ServerCertVerifier};
use rustls::pki_types::{CertificateDer, ServerName, UnixTime};
use rustls::server::danger::{ClientCertVerified, ClientCertVerifier};
use rustls::{DigitallySignedStruct, DistinguishedName, RootCertStore, SignatureScheme};
use std::sync::Arc;
use x509_parser::prelude::*;

/// Server certificate verifier for WezTerm client.
///
/// This verifier accepts certificates signed by a specific CA (the WezTerm PKI CA).
/// It optionally skips hostname verification for local connections.
#[derive(Debug)]
pub struct WezTermCertVerifier {
    ca_cert_der: CertificateDer<'static>,
    accept_invalid_hostnames: bool,
}

impl WezTermCertVerifier {
    /// Create a new verifier that trusts certificates signed by the given CA.
    pub fn new(ca_cert: CertificateDer<'static>, accept_invalid_hostnames: bool) -> Result<Self> {
        // Validate that we can parse the CA certificate
        let _ = X509Certificate::from_der(ca_cert.as_ref())
            .map_err(|e| anyhow!("Failed to parse CA certificate: {:?}", e))?;

        Ok(Self {
            ca_cert_der: ca_cert,
            accept_invalid_hostnames,
        })
    }
}

impl ServerCertVerifier for WezTermCertVerifier {
    fn verify_server_cert(
        &self,
        end_entity: &CertificateDer<'_>,
        _intermediates: &[CertificateDer<'_>],
        server_name: &ServerName<'_>,
        _ocsp_response: &[u8],
        now: UnixTime,
    ) -> Result<ServerCertVerified, rustls::Error> {
        // Parse the server certificate
        let (_, cert) = X509Certificate::from_der(end_entity.as_ref()).map_err(|_| {
            rustls::Error::InvalidCertificate(rustls::CertificateError::BadEncoding)
        })?;

        // Parse our trusted CA
        let (_, ca_cert) = X509Certificate::from_der(self.ca_cert_der.as_ref()).map_err(|_| {
            rustls::Error::InvalidCertificate(rustls::CertificateError::BadEncoding)
        })?;

        // Verify the certificate is signed by our CA
        cert.verify_signature(Some(ca_cert.public_key()))
            .map_err(|_| {
                rustls::Error::InvalidCertificate(rustls::CertificateError::BadSignature)
            })?;

        // Check validity period
        let now_secs = now.as_secs();
        if !cert.validity().is_valid_at(
            x509_parser::time::ASN1Time::from_timestamp(now_secs as i64)
                .expect("valid timestamp"),
        ) {
            return Err(rustls::Error::InvalidCertificate(
                rustls::CertificateError::Expired,
            ));
        }

        // Optionally verify the server name matches
        if !self.accept_invalid_hostnames {
            let expected_name = match server_name {
                ServerName::DnsName(name) => name.as_ref(),
                _ => {
                    return Err(rustls::Error::InvalidCertificate(
                        rustls::CertificateError::ApplicationVerificationFailure,
                    ))
                }
            };

            // Check CN and SANs
            let mut name_matches = false;

            // Check Subject CN
            if let Some(cn) = cert
                .subject()
                .iter_common_name()
                .next()
                .and_then(|cn| cn.as_str().ok())
            {
                if cn == expected_name || cn == "*" {
                    name_matches = true;
                }
            }

            // Check Subject Alternative Names
            if !name_matches {
                if let Ok(Some(san_ext)) = cert.subject_alternative_name() {
                    for name in &san_ext.value.general_names {
                        if let GeneralName::DNSName(dns_name) = name {
                            if *dns_name == expected_name || *dns_name == "*" {
                                name_matches = true;
                                break;
                            }
                        }
                    }
                }
            }

            if !name_matches {
                return Err(rustls::Error::InvalidCertificate(
                    rustls::CertificateError::ApplicationVerificationFailure,
                ));
            }
        }

        Ok(ServerCertVerified::assertion())
    }

    fn verify_tls12_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &DigitallySignedStruct,
    ) -> Result<HandshakeSignatureValid, rustls::Error> {
        rustls::crypto::verify_tls12_signature(
            message,
            cert,
            dss,
            &rustls::crypto::ring::default_provider().signature_verification_algorithms,
        )
    }

    fn verify_tls13_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &DigitallySignedStruct,
    ) -> Result<HandshakeSignatureValid, rustls::Error> {
        rustls::crypto::verify_tls13_signature(
            message,
            cert,
            dss,
            &rustls::crypto::ring::default_provider().signature_verification_algorithms,
        )
    }

    fn supported_verify_schemes(&self) -> Vec<SignatureScheme> {
        rustls::crypto::ring::default_provider()
            .signature_verification_algorithms
            .supported_schemes()
    }
}

/// Client certificate verifier for WezTerm mux server.
///
/// This verifier:
/// 1. Requires a client certificate (mutual TLS)
/// 2. Verifies the certificate is signed by the trusted CA
/// 3. Verifies the CN matches the Unix username running the server
#[derive(Debug)]
pub struct WezTermClientCertVerifier {
    root_store: Arc<RootCertStore>,
    subjects: Vec<DistinguishedName>,
}

impl WezTermClientCertVerifier {
    /// Create a new client verifier with the given root certificate store.
    pub fn new(root_store: RootCertStore) -> Result<Self> {
        let subjects = root_store
            .roots
            .iter()
            .map(|ta| DistinguishedName::from(ta.subject.as_ref().to_vec()))
            .collect();

        Ok(Self {
            root_store: Arc::new(root_store),
            subjects,
        })
    }

    /// Verify that the client certificate CN matches the expected Unix username.
    pub fn verify_cn(cert: &CertificateDer<'_>) -> Result<(), rustls::Error> {
        let (_, x509_cert) = X509Certificate::from_der(cert.as_ref()).map_err(|_| {
            rustls::Error::InvalidCertificate(rustls::CertificateError::BadEncoding)
        })?;

        // Get the CN from the certificate
        let cn = x509_cert
            .subject()
            .iter_common_name()
            .next()
            .and_then(|cn| cn.as_str().ok())
            .ok_or_else(|| {
                rustls::Error::InvalidCertificate(
                    rustls::CertificateError::ApplicationVerificationFailure,
                )
            })?;

        // Get expected username from environment
        #[cfg(unix)]
        let wanted_unix_name = std::env::var("USER").unwrap_or_default();
        #[cfg(windows)]
        let wanted_unix_name = std::env::var("USERNAME").unwrap_or_default();

        // Check if CN matches directly
        if cn == wanted_unix_name {
            log::trace!(
                "Peer certificate CN `{}` == $USER `{}`",
                cn,
                wanted_unix_name
            );
            return Ok(());
        }

        // Check for encoded format: user:unixname/DATA
        let maybe_encoded = format!("user:{}/", wanted_unix_name);
        if cn.starts_with(&maybe_encoded) {
            log::trace!(
                "Peer certificate CN `{}` matches $USER `{}`",
                cn,
                wanted_unix_name
            );
            return Ok(());
        }

        log::error!(
            "CN `{}` did not match expected user `{}`",
            cn,
            wanted_unix_name
        );
        Err(rustls::Error::InvalidCertificate(
            rustls::CertificateError::ApplicationVerificationFailure,
        ))
    }
}

impl ClientCertVerifier for WezTermClientCertVerifier {
    fn root_hint_subjects(&self) -> &[DistinguishedName] {
        &self.subjects
    }

    fn verify_client_cert(
        &self,
        end_entity: &CertificateDer<'_>,
        intermediates: &[CertificateDer<'_>],
        now: UnixTime,
    ) -> Result<ClientCertVerified, rustls::Error> {
        // First, verify the certificate chain against our root store
        // Parse the certificate
        let (_, cert) = X509Certificate::from_der(end_entity.as_ref()).map_err(|_| {
            rustls::Error::InvalidCertificate(rustls::CertificateError::BadEncoding)
        })?;

        // Check validity
        let now_secs = now.as_secs();
        if !cert.validity().is_valid_at(
            x509_parser::time::ASN1Time::from_timestamp(now_secs as i64)
                .expect("valid timestamp"),
        ) {
            return Err(rustls::Error::InvalidCertificate(
                rustls::CertificateError::Expired,
            ));
        }

        // Verify the certificate is signed by a trusted root CA
        // We need to cryptographically verify the signature, not just compare DNs
        let mut verified_against_root = false;

        for root in &self.root_store.roots {
            // Parse the root CA certificate from the trust anchor
            let root_subject = &root.subject;
            let cert_issuer = cert.issuer().as_raw();

            // First check if issuer DN matches root subject DN
            if root_subject.as_ref() != cert_issuer {
                continue;
            }

            // DN matches, now verify the cryptographic signature
            // The root's subject_public_key_info contains the public key
            if let Ok((_, root_spki)) =
                x509_parser::prelude::SubjectPublicKeyInfo::from_der(
                    root.subject_public_key_info.as_ref()
                )
            {
                // Verify the end-entity certificate's signature using the root's public key
                if cert.verify_signature(Some(&root_spki)).is_ok() {
                    verified_against_root = true;
                    log::trace!("Certificate verified against root CA");
                    break;
                }
            }
        }

        // Also check intermediates can chain to root
        if !verified_against_root && !intermediates.is_empty() {
            // Build a chain: end_entity -> intermediates -> root
            // Verify each link in the chain cryptographically
            let mut current_cert = cert.clone();

            for intermediate in intermediates {
                if let Ok((_, int_cert)) = X509Certificate::from_der(intermediate.as_ref()) {
                    // Check if current cert was issued by this intermediate
                    if current_cert.issuer().as_raw() == int_cert.subject().as_raw() {
                        // Verify signature
                        if current_cert.verify_signature(Some(int_cert.public_key())).is_ok() {
                            // Move up the chain
                            current_cert = int_cert;

                            // Check if intermediate chains to a root
                            for root in &self.root_store.roots {
                                if root.subject.as_ref() == current_cert.issuer().as_raw() {
                                    if let Ok((_, root_spki)) =
                                        x509_parser::prelude::SubjectPublicKeyInfo::from_der(
                                            root.subject_public_key_info.as_ref()
                                        )
                                    {
                                        if current_cert.verify_signature(Some(&root_spki)).is_ok() {
                                            verified_against_root = true;
                                            log::trace!("Certificate chain verified against root CA");
                                            break;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                if verified_against_root {
                    break;
                }
            }
        }

        if !verified_against_root {
            log::error!("Client certificate not issued by trusted CA (signature verification failed)");
            return Err(rustls::Error::InvalidCertificate(
                rustls::CertificateError::UnknownIssuer,
            ));
        }

        // Verify the CN matches the Unix username
        Self::verify_cn(end_entity)?;

        Ok(ClientCertVerified::assertion())
    }

    fn verify_tls12_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &DigitallySignedStruct,
    ) -> Result<HandshakeSignatureValid, rustls::Error> {
        rustls::crypto::verify_tls12_signature(
            message,
            cert,
            dss,
            &rustls::crypto::ring::default_provider().signature_verification_algorithms,
        )
    }

    fn verify_tls13_signature(
        &self,
        message: &[u8],
        cert: &CertificateDer<'_>,
        dss: &DigitallySignedStruct,
    ) -> Result<HandshakeSignatureValid, rustls::Error> {
        rustls::crypto::verify_tls13_signature(
            message,
            cert,
            dss,
            &rustls::crypto::ring::default_provider().signature_verification_algorithms,
        )
    }

    fn supported_verify_schemes(&self) -> Vec<SignatureScheme> {
        rustls::crypto::ring::default_provider()
            .signature_verification_algorithms
            .supported_schemes()
    }

    fn client_auth_mandatory(&self) -> bool {
        true // WezTerm mux requires client certificates
    }
}

/// Extract the Common Name (CN) from a certificate.
pub fn extract_cn(cert: &CertificateDer<'_>) -> Result<String> {
    let (_, x509_cert) = X509Certificate::from_der(cert.as_ref())
        .map_err(|e| anyhow!("Failed to parse certificate: {:?}", e))?;

    let cn = x509_cert
        .subject()
        .iter_common_name()
        .next()
        .and_then(|cn| cn.as_str().ok())
        .ok_or_else(|| anyhow!("Certificate has no CN"))?;

    Ok(cn.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use rcgen::CertificateParams;

    fn generate_test_ca() -> CertificateDer<'static> {
        // Use rcgen 0.12 API
        let mut params = CertificateParams::new(vec!["Test CA".into()]);
        params.is_ca = rcgen::IsCa::Ca(rcgen::BasicConstraints::Unconstrained);

        let cert = rcgen::Certificate::from_params(params).unwrap();
        CertificateDer::from(cert.serialize_der().unwrap())
    }

    #[test]
    fn test_wezterm_cert_verifier_creation() {
        let ca_cert = generate_test_ca();
        let verifier = WezTermCertVerifier::new(ca_cert, false);
        assert!(verifier.is_ok());
    }

    #[test]
    fn test_extract_cn() {
        // Use rcgen 0.12 API - note: generate_simple_self_signed uses
        // "rcgen self signed cert" as CN, the input becomes a SAN
        let cert = rcgen::generate_simple_self_signed(vec!["test-cn.example.com".into()]).unwrap();
        let cert_der = CertificateDer::from(cert.serialize_der().unwrap());

        let cn = extract_cn(&cert_der);
        assert!(cn.is_ok());
        // rcgen 0.12 uses this default CN for generate_simple_self_signed
        assert_eq!(cn.unwrap(), "rcgen self signed cert");
    }
}
